services:
  postgres_db:
    image: postgres:16
    container_name: postgres
    environment:
      POSTGRES_USER: pms
      POSTGRES_PASSWORD: supersecretpassword
      POSTGRES_DB: products
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U pms -d products"]
      interval: 5s
      timeout: 3s
      retries: 20

  pgadmin:
      image: dpage/pgadmin4:latest
      container_name: pgadmin
      depends_on:
        postgres_db:
          condition: service_healthy
      ports:
        - "5050:80"
      environment:
        PGADMIN_DEFAULT_EMAIL: admin@local.com
        PGADMIN_DEFAULT_PASSWORD: admin
      volumes:
        - pgadmin_data:/var/lib/pgadmin

  pms_app:
    container_name: pms_app
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      postgres_db:
        condition: service_healthy
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres_db:5432/products
      SPRING_DATASOURCE_USERNAME: pms
      SPRING_DATASOURCE_PASSWORD: supersecretpassword

      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: "true"
      SPRING_JPA_PROPERTIES_HIBERNATE_FORMAT_SQL: "true"
      LOGGING_LEVEL_ORG_HIBERNATE_SQL: debug
      LOGGING_LEVEL_ORG_HIBERNATE_TOOL_SCHEMA: debug

      MEDIA_STORAGE_TYPE: filesystem
      MEDIA_BASE_PATH: /workspace/.data/media

      SPRING_DEVTOOLS_RESTART_ENABLED: "true"
      SPRING_DEVTOOLS_RESTART_POLL_INTERVAL: "2s"
    volumes:
      - ./app:/workspace
      - maven_repo:/root/.m2

volumes:
  postgres_data:
  maven_repo:
  pgadmin_data: